### ISSUE TITLE
Firebase plugin is not loading

### ISSUE THREAD

**Issue by vundurty** [Chadori/construct-master-collection#135]
I have a problem. I have added the firebase plugin to a project when I preview it, it doesn't load.

I have recorded the issue - https://drive.google.com/file/d/1KD7-HVIlBFuPix0QBbX1i4zQsAeM32qs/view?usp=sharing

Please help.

**Comment by vundurty** [comment]
Console Logs
https://drive.google.com/file/d/1hMHwyUgxFz7HYB7TrU-k9TjbUfU513vO/view?usp=sharing
https://drive.google.com/file/d/1aLQHA4ajRKHbDhj1KJX6e29Y29aZpH6w/view?usp=sharing

**Comment by Beelzaboss** [comment]
You need to disable Web Worker in the Project settings.

**Comment by Beelzaboss** [comment]
Add me on discord BlinkFX#2127

**Comment by Chadori** [comment]
Similar problem with: https://github.com/ChadoriRebornXD/Construct-Master-Collection/issues/134

Should be fixed on the next release.
Thanks for reporting.

**Comment by Chadori** [comment]
Hi, it seems that it's a problem on the **Firebase Console** side, I've tried it on a test project.

![image](https://user-images.githubusercontent.com/31282960/65912561-fb5fc000-e400-11e9-88c2-9ff92c13cf19.png)

Maybe you can instead check your Firebase Console or credentials side. 
I'll close this for now, let me know if you have other problems on a separate issue.

**Comment by Chadori** [comment]
Also, in case of related or other Firebase issues, I don't use the Firebase Master Collection on my own projects anymore, so if anyone can present a reproducible project, even through private message or email.
**I would be glad to prioritize its repair, since I'm not sure if it's high-quality anymore, since I haven't used it for months now.**

Thanks.

**Comment by vundurty** [comment]
Hi 

It doesn't work for me. I tired with test credentials, it's still the same. It doesn't load.

Please check the test C3P.

[FirebaseTest.zip](https://github.com/ChadoriRebornXD/Construct-Master-Collection/files/3693627/FirebaseTest.zip)

**Comment by Chadori** [comment]
Hello. 

First, you need to disable the experimental feature, the **worker**.
![image](https://user-images.githubusercontent.com/31282960/66264305-53e5f180-e835-11e9-96c5-c7f9a0ad4954.png)


Then, use your own Firebase Credentials, I don't recall adding any test credentials for Firebase, it might be a leftover credentials from the old C2 version. 
I recommend everyone to use their own.

Here's a tutorial I've found that could help you:
https://shatter-box.com/knowledgebase/firebase-sync-data-with-your-construct-2-game/

**Comment by vundurty** [comment]
I didn't know this. This was a miss from my end. Thanks alot for explaining. It works now.
